homeassistant:
  # Name of the location where Home Assistant is running
  name: ToJo Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.161458
  longitude: 4.832792
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 74 // TODO: Check
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels
