language: python
python:
  - "3.5"
install: 
  - "pip install homeassistant"
  - "bash $TRAVIS_BUILD_DIR/bin/dummy_secrets.sh"
  - "sudo touch /dev/ttyUSB0"
script: "bash $TRAVIS_BUILD_DIR/bin/check_config.sh"
notifications:
  email: false
