- id: '1582462134427'
  alias: gang lichten plafond
  description: ''
  trigger:
  - entity_id: binary_sensor.day_night
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.gang_boven_licht
    state: 'on'
  action:
  - data: {}
    entity_id: light.gang_boven
    service: light.turn_on
- id: '1582462140881'
  alias: gang lichten muur
  description: ''
  trigger:
  - entity_id: binary_sensor.day_night
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.gang_boven_licht
    state: 'on'
  action:
  - data: {}
    entity_id: light.gang_boven_muur
    service: light.turn_on
