homeassistant:
  name: !secret general.name
  latitude: !secret general.latitude
  longitude: !secret general.longitude
  elevation: !secret general.elevation
  unit_system: metric
  time_zone: Europe/Brussels

  # Load packages
  packages: !include_dir_named integrations
