homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.2731
  longitude: 4.6653
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 74
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels

  customize: !include customize.yaml
  customize_glob:
    "sensor.system_monitor_process_*":
      hidden: true
logger:
  default: warning
  logs:
    requests.packages.urllib3: error

# Enables the frontend
frontend:

config:

panel_iframe:
  plexpy:
    title: 'PlexPy'
    url: !secret plexpy.url
    icon: mdi:eye
  flexget:
    title: 'Flexget'
    url: !secret flexget.url
    icon: mdi:cloud-download
  deluge:
    title: 'Deluge'
    url: !secret deluge.url
    icon: mdi:download

http:
  api_password: !secret http.password
  ssl_certificate: !secret http.ssl.cert
  ssl_key: !secret http.ssl.key
  base_url: !secret http.base.url
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
#discovery:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 14
  db_url: !secret db_url

# View all events in a logbook
logbook:

google:
  client_id: !secret google.id
  client_secret: !secret google.secret

calendar:
  - platform: google
    client_id: !secret google.id
    client_secret: !secret google.secret

# Track the sun
#sun:

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.0/24
    home_interval: 5
    scan_interval: 30
    interval_seconds: 30

############# Demo stuff
weather:
  - platform: openweathermap
    api_key: !secret owm.api

binary_sensor:
#  - platform: flexget
 #   password: !secret flexget
  - platform: template
    sensors:
      free_space_low:
        value_template: "{{ states.sensor.system_monitor_disk_free_plexmediaserver.state | float < 100 }}"

media_player:
  - platform: plex
    include_non_clients: true
  - platform: spotify
    client_id: !secret spotify.id
    client_secret: !secret spotify.secret

####################
#   Includes       #
####################
zone: !include_dir_merge_list zone/
automation: !include_dir_list automation/
group: !include_dir_named group/
sensor: !include_dir_list sensor/
script: !include_dir_named script/
shell_command: !include_dir_named shell_command/
alert: !include alert.yaml
notify: !include_dir_list notify/
