homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.2731
  longitude: 4.6653
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 74
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels

  customize: !include customize.yaml
  customize_glob:
    "sensor.system_monitor_process_*":
      hidden: true
logger:
  default: warning
  logs:
    requests.packages.urllib3: error

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.1.201:8081
    name: Front Door

# Enables the frontend
frontend:

config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 14
  db_url: !secret db_url

# View all events in a logbook
logbook:

google:
  client_id: 72083380627-0itnt9cn81ivs7i5a71r583qrg85k6hc.apps.googleusercontent.com
  client_secret: !secret google_secret

calendar:
  - platform: google
    client_id: 72083380627-0itnt9cn81ivs7i5a71r583qrg85k6hc.apps.googleusercontent.com
    client_secret: !secret google_secret

logger:
  default: debug
  logs:
    homeassistant.components.rfxtrx: warning

rfxtrx:
  device: /dev/ttyUSB0

# Track the sun
#sun:
# Notifier setup
notify:
  - name: pushbullet_tom
    platform: pushbullet
    api_key: !secret pushbullet_api

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.0/24
    home_interval: 5
    scan_interval: 30
    interval_seconds: 30

############# Demo stuff
weather:
  - platform: openweathermap
    api_key: !secret owm_api

#alarm_control_panel:
 # - platform: demo

binary_sensor:
  - platform: flexget
    password: !secret flexget
 # - platform: demo

#camera:
 # - platform: demo

#climate: 
 # - platform: demo

#cover:
 # - platform: demo

#fan:
#  - platform: demo

#light:
 # - platform: demo

#lock:
 # - platform: demo

#remote:
 # - platform: demo

switch:
  - platform: rfxtrx
    automatic_add: True
    devices:
      0b11000000f5f11e01010f50:
        name: staande_lampen
      0b11000103bc0cfe01010f70:
        name: living_staande_lamp
      0b11000124bc0cfe03010f70:
        name: dj_staande_lamp
      0b11000622bc0cfe04010f70:
        name: eet_staande_lamp
      0b11000600f5f11e02010f50:
        name: scene1
        fire_event: True
      0b11000100f5f11e03000060:
        name: scene2
        fire_event: True
      7100a0341040000:
        name: kerst
 # - platform: demo

#tts:
 # - platform: demo

media_player:
  - platform: plex

####################
#   Includes       #
####################
zone: !include_dir_merge_list zone/
automation: !include_dir_list automation/
group: !include_dir_named group/
sensor: !include_dir_list sensor/
script: !include_dir_named script/
shell_command: !include_dir_named shell_command/
