homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.2731
  longitude: 4.6653
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 74
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 14
  db_url: !secret db_url

# View all events in a logbook
logbook:

google:
  client_id: 72083380627-0itnt9cn81ivs7i5a71r583qrg85k6hc.apps.googleusercontent.com
  client_secret: !secret google_secret

calendar:
  - platform: google
    client_id: 72083380627-0itnt9cn81ivs7i5a71r583qrg85k6hc.apps.googleusercontent.com
    client_secret: !secret google_secret

# Track the sun
sun:
# Notifier setup
notify:
  - name: pushbullet_tom
    platform: pushbullet
    api_key: !secret pushbullet_api

shell_command:
  get_latest_config: bash /home/hass/.homeassistant/bin/pullconfig.sh

#script:
#  update_config:
 #   sequence:
  #    - service: shell_command.get_latest_config
   #   - service: homeassistant.restart

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.0/24
    home_interval: 5
  - platform: owntracks

mqtt:
  broker: m21.cloudmqtt.com
  port: 23101
  username: !secret mqtt_username
  password: !secret mqtt_pass
 

############# Demo stuff
#alarm_control_panel:
 # - platform: demo

#binary_sensor:
 # - platform: demo

#camera:
 # - platform: demo

#climate: 
 # - platform: demo

#cover:
 # - platform: demo

#fan:
#  - platform: demo

#light:
 # - platform: demo

#lock:
 # - platform: demo

#remote:
 # - platform: demo

#switch:
 # - platform: demo

#tts:
 # - platform: demo

####################
#   Includes       #
####################
zone: !include_dir_merge_list zone/
automation: !include_dir_list automation/
group: !include_dir_named group/
sensor: !include_dir_list sensor/
script: !include_dir_named script/
