platform: xiaomi_cgg1
mac_address: 58:2D:34:11:2C:40
temperature:
  name: "Dining Room Temperature Xiaomi"
humidity:
  name: "Dining Room Humidity Xiaomi"
battery_level:
  name: "Dining Room Battery Xiaomi"