---
# Ethernet component package
#
# Contains the ethernet setup.
#
# https://esphome.io/components/ethernet.html
#
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO5