alias: "Get Latest Config"
sequence:
  - service: shell_command.update_new_commits_sensor
  - condition: numeric_state
    entity_id: sensor.new_commits
    above: 0
  - service: shell_command.get_latest_config
  - service: homeassistant.restart
