alias: "Get Latest Config"
sequence:
  - condition: numeric_state
    entity_id: shell_command.command_sensor
    above: 0
  - service: shell_command.get_latest_config
  - service: homeassistant.restart
