---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret WIFI_SSID
  wifi_password: !secret WIFI_PASSWORD
  
wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  fast_connect: true
