packages:
  <<: !include_dir_named ../common/
  board: !include ../boards/quinled_esp32.yaml
  ethernet: !include ../components/ethernet.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy: