packages:
  <<: !include_dir_named ../common/
  board: !include ../boards/quinled_esp32.yaml
  ethernet: !include  ../components/ethernet.yaml

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:
  scan_parameters:
    window: 300ms
