packages:
  <<: !include_dir_named ../common/
  board: !include ../boards/esp8266_d1_mini.yaml

<<: !include ../components/i2c.yaml

sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    update_interval: 100ms
    internal: True
    id: distance

binary_sensor:
  - platform: template
    name: "${name} Triggered"
    lambda: |-
      if (id(distance).state < 0.70) {
        // Beam was broken
        return true;
      } else {
        return false;
      }