alias: Monthly bandwidth usage reached
trigger:
  platform: numeric_state
  entity_id: sensor.monthly_bandwidth_usage
  above: 300
action:
  service: notify.tom
  data:
    title: "Slow down your downloading"
    message: "You have reached your soft limit of downloading, consider putting some stuff on hold for a while"
