alias: Free space
trigger:
  platform: numeric_state
  entity_id: sensor.system_monitor_disk_free_plexmediaserver
  below: 100
action:
  service: notify.all
  data:
    title: "Disk space low"
    message: "Disk space of your server is low, remaining: {{ states.sensor.system_monitor_disk_free_plexmediaserver.state }} GiB"
