alias: Free space Danger
trigger:
  platform: numeric_state
  entity_id: sensor.system_monitor_disk_free_plexmediaserver
  below: 50
action:
  service: notify.all
  data:
    title: "Disk space very low"
    message: "Disk space of your server is very low, clear some stuff damnit!"
