alias: "Adding device failure"
trigger:
  platform: event
  event_type: new_device_update_failed
action:
  - service: persistent_notification.create
    data_template:
      title: "Adding device to Github failed"
      message: >
        HA couldn't add a new device to github
        {{ trigger.event.event_data }}
