packages:
  device: !include devices/bluetooth_node.yaml 

substitutions:
  slug: bluetooth-node-upstairs-laundry-room
  name: Bluetooth Node Upstairs Laundy Room
  description: Bluetooth aggregation node, upstairs in the laundry room.

sensor:
  - <<: !include ble-devices/xiaomi_bathroom.yaml
  - <<: !include ble-devices/xiaomi_bedroom.yaml
  - <<: !include ble-devices/xiaomi_laundry_room.yaml