packages:
  device: !include devices/bluetooth_node_ethernet.yaml 

substitutions:
  slug: bt-node-upstairs-laundry-room
  name: BT Node Upstairs Laundy Room
  description: Bluetooth aggregation node, upstairs in the laundry room.

sensor:
  - <<: !include ble-devices/xiaomi_bathroom.yaml
  - <<: !include ble-devices/xiaomi_bedroom.yaml
  - <<: !include ble-devices/xiaomi_laundry_room.yaml