esphome:
  name: downstairs_node_aggregation
  platform: ESP32
  board: mhetesp32minikit
  
wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  fast_connect: true
  
api:

logger:

ota:
  password: !secret OTA_PASSWORD
  
# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:
  scan_parameters:
    active: false

sensor:
  - platform: xiaomi_cgg1
    mac_address: 58:2D:34:11:30:1C
    temperature:
      name: "XIAOMI 582D3411301C Temperature"
    humidity:
      name: "XIAOMI 582D3411301C Humidity"
    battery_level:
      name: "XIAOMI 582D3411301C Battery"
  - platform: xiaomi_cgg1
    mac_address: 58:2D:34:11:2C:40
    temperature:
      name: "XIAOMI 582D34112C40 Temperature"
    humidity:
      name: "XIAOMI 582D34112C40 Humidity"
    battery_level:
      name: "XIAOMI 582D34112C40 Battery"
  - platform: xiaomi_cgg1
    mac_address: 58:2D:34:11:2F:8E
    temperature:
      name: "XIAOMI 582D34112F8E Temperature"
    humidity:
      name: "XIAOMI 582D34112F8E Humidity"
    battery_level:
      name: "XIAOMI 582D34112F8E Battery"