esphome:
  name: staircase_upstairs_to_downstairs
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  fast_connect: true
  
logger:
  level: info

api:

ota:
  password: !secret OTA_PASSWORD
 
i2c:
  sda: GPIO3
  scl: GPIO0
  scan: True
  
sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    update_interval: 0.2s
    internal: True
    id: distance

binary_sensor:
  - platform: template
    name: "Beam broken"
    lambda: |-
      if (id(distance).state < 0.70) {
        // Beam was broken
        return true;
      } else {
        return false;
      }