esphome:
  name: staircase_downstairs
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  fast_connect: true

logger:
  level: info

api:

ota:
  password: !secret OTA_PASSWORD

i2c:
  scan: True

sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    update_interval: 100ms
    internal: True
    id: distance

binary_sensor:
  - platform: template
    name: "Staircase Downstairs Triggered"
    lambda: |-
      if (id(distance).state < 0.70) {
        // Beam was broken
        return true;
      } else {
        return false;
      }